### ISSUE TITLE
add the UITextView-Placeholder category to my Project cause crash

### ISSUE THREAD

**Issue by bupojung** [devxoul/UITextView-Placeholder#14]
I add the category to my project, when i dismiss a viewcontroller with a UITextView, there is a crash. i didn't even import the header file

**Comment by devxoul** [comment]
Hi @bupojung,

Could you please tell me 1) which version are you using and 2) what error message did you see?

Thanks.

**Comment by iosdv** [comment]
Crashing in `swizzledDealloc` and in `[self removeObserver:self forKeyPath:key];` not find observer for key

**Comment by devxoul** [comment]
@iosdv, is that really a 'Crash'? (Not a exception breakpoint?)

**Comment by iosdv** [comment]
Sorry @devxoul  I have not updated the library. I think It's now fixed.

**Comment by devxoul** [comment]
@iosdv, great :smile::+1:

@bupojung, ping

**Comment by devxoul** [comment]
Close due to long time no response. Please reopen this issue if needed :smile:
