### ISSUE TITLE
TextView resets text if focused again

### ISSUE THREAD

**Issue by zeshanhayder** [devxoul/UITextView-Placeholder#17]
UiTextView resets the text inside it and places placeholder label even if there is text inside textview written by user. unfocus the textview and then focus again... all text cleared.

**Comment by devxoul** [comment]
@zeshanhayder can you attach screenshots or video?

**Comment by zeshanhayder** [comment]
<img width="339" alt="screen shot 2015-10-28 at 11 39 58 am" src="https://cloud.githubusercontent.com/assets/528785/10781424/b696e5e6-7d68-11e5-9b1f-f1dfaa2a9e38.png">
Added Comment


<img width="332" alt="screen shot 2015-10-28 at 11 40 04 am" src="https://cloud.githubusercontent.com/assets/528785/10781428/becd5826-7d68-11e5-84f8-eadeae9da2a7.png">


Lost Focus


<img width="332" alt="screen shot 2015-10-28 at 11 40 10 am" src="https://cloud.githubusercontent.com/assets/528785/10781429/c28b6b92-7d68-11e5-97f5-637a22413aaf.png">
After getting focus back.

**Comment by devxoul** [comment]
What is placeholder? The `MESSAGE`?

**Comment by zeshanhayder** [comment]
ye

**Comment by devxoul** [comment]
@zeshanhayder, could you show me your code?

**Comment by zeshanhayder** [comment]
i just implemented .placeholder property of your category and included category as well.

self.tvMessage.textColor = placeHolderColor;
    self.tvMessage.placeholder = eloc;
    self.tvMessage.delegate = self;

**Comment by devxoul** [comment]
Which environment did you test?

**Comment by zeshanhayder** [comment]
ios 9 - iphone 6

**Comment by devxoul** [comment]
Does it occurred with bare project? I've tested with this code but cannot reproduce it.

```objective-c
#import "ViewController.h"
#import "UITextView+Placeholder.h"

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    UITextView *textView = [[UITextView alloc] init];
    textView.frame = CGRectMake(0, 20, CGRectGetWidth(self.view.bounds), 100);
    textView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    textView.placeholder = @"My Placeholder";
    textView.font = [UIFont systemFontOfSize:15];
    [self.view addSubview:textView];

    UITapGestureRecognizer *recognizer = [[UITapGestureRecognizer alloc] initWithTarget:self
                                                                                 action:@selector(didTapBackground)];
    [self.view addGestureRecognizer:recognizer];
}

- (void)didTapBackground {
    [self.view endEditing:YES];
}

@end
```

**Comment by zeshanhayder** [comment]
thats strange. it happens to me everytime.

**Comment by devxoul** [comment]
@zeshanhayder On your real iPhone 6 device? (Unfortunately I don't have iPhoen 6 device :cry:)

**Comment by zeshanhayder** [comment]
no even on simulator it does the same. i will try to upload a video asap i got free time

**Comment by devxoul** [comment]
@zeshanhayder Thanks.

**Comment by devxoul** [comment]
Please reopen it when you available :)
