### ISSUE TITLE
delloc error

### ISSUE THREAD

**Issue by NagiYan** [devxoul/UITextView-Placeholder#18]
crash stack:
[UITextView dealloc]
[UITextView dealloc]
...
...
...
[UITextView dealloc]
[UITextView dealloc]
[UITextView dealloc]

ios9.1
only if I put your files in my project, delloc crash, remove files then ok.

**Comment by devxoul** [comment]
Could you please how did you setup UITextView-Placeholder in your project? Or the code using UITextView.

**Comment by NagiYan** [comment]
I put the h and m files in my project, 
    // 输入框

    input = [[UITextView new] autorelease];
    [containor addSubview:input];
    [input mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(back).with.offset(10);
        make.right.equalTo(back).with.offset(-10);
        make.top.equalTo(back);
        make.height.equalTo(@100);
    }];
    [input setText:@"placeholder"];

everywhere i user uitextview, nomatter use or not use placeholder, even uisearchbar,when delloc, crash

**Comment by devxoul** [comment]
Did you mean the infinite recursive dealloc call?

**Comment by NagiYan** [comment]
yes!

**Comment by devxoul** [comment]
OK, thank you for report. I'll check it soon. :smile:

**Comment by devxoul** [comment]
@NagiYan, could you please test with new project?

**Comment by NagiYan** [comment]
where is the new version?

**Comment by devxoul** [comment]
Not a new version. Create a new project and add UITextView+Placeholder. Does it crash?

**Comment by NagiYan** [comment]
new project is ok...

**Comment by NagiYan** [comment]
i tryed to update all my pods, it seems ok now

**Comment by devxoul** [comment]
Cool! If it crashes again, please reopen it.
