### ISSUE TITLE
the attributedPlaceholder font  will be overrided.

### ISSUE THREAD

**Issue by aelam** [devxoul/UITextView-Placeholder#20]
- (void)updatePlaceholderLabel {
            // ...
            self.placeholderLabel.font = self.font;        
            // ...
       }

see the code. the font of attributedPlaceholder's will be overrided.

**Comment by livv** [comment]
I also encountered this problem

**Comment by aelam** [comment]
You can checkout my fork first

**Comment by devxoul** [comment]
Hey guys! Sorry for delay. :pray: I had very busy days. I'll take a look for it as soon as possible.

@aelam As I mentioned in comment, I cannot merge #21 right now.

**Comment by aelam** [comment]
You can fix on your way just ignore that merge

**Comment by devxoul** [comment]
@aelam, could you please test with #27? If you're using CocoaPods, you can just update **`Podfile`**.

```ruby
pod 'UITextView+Placeholder', :git => 'https://github.com/devxoul/UITextView-Placeholder', :branch => 'font-override'
```

**Comment by aelam** [comment]
It works!
