### ISSUE TITLE
Multiple calls of `load` after integrating

### ISSUE THREAD

**Issue by angelolloqui** [devxoul/UITextView-Placeholder#22]
We are experiencing multiple calls of the `load` method after introducing the library. I believe it is due to the call to `[super load]` found in [UITextView-Placeholder.m ](https://github.com/devxoul/UITextView-Placeholder/blob/master/UITextView%2BPlaceholder/UITextView%2BPlaceholder.m#L33)

Call to `[super load]` should be omitted, the system will already call `load` itself for each class.

**Comment by devxoul** [comment]
@angelolloqui, thanks for your report. #23 is the patch of it.
Check please then I can merge and release the new version :)

**Comment by angelolloqui** [comment]
Woow! that was quick! It works indeed. We have tried in our project, and by removing this we get a single call to load in parent classes, as expected.

**Comment by devxoul** [comment]
Cool! I've just made a new release 1.1.1 and also uploaded to CocoaPods.

**Comment by angelolloqui** [comment]
Thanks man! awesome response time! I wish I would take so serious my own shit :) 

Cheers!

**Comment by devxoul** [comment]
I was *githubbing* at that time. Thanks!
