### ISSUE TITLE
TextView frame의 Center에 맞게 고쳐주세요

### ISSUE THREAD

**Issue by ehowlsla** [devxoul/UITextView-Placeholder#30]
입력시 textview 첫째줄 위치에 placeholder가 위치하는데

textview 높이가 클 시에 가운데 에 맞춰서 placeholder 기능이 되도록 수정해주세요

[](url)
![simulator screen shot 2016 4 26 3 45 14](https://cloud.githubusercontent.com/assets/1625573/14809157/11c3a184-0bc6-11e6-84cc-3e10159da1b1.png)

**Comment by ehowlsla** [comment]
하단의 내용을 입력하세요가 가운데에 가도록~

**Comment by devxoul** [comment]
안녕하세요. UITextView+Placeholder는 UITextView의 텍스트 행동을 따라가도록 디자인되었습니다. UITextView에서는 기본적으로 모든 텍스트가 세로 상단 정렬이므로, Placeholder 또한 상단에 위치하는게 맞습니다.

그리고, 이곳은 한국어 사용자들만을 위한 공간이 아니기 때문에 다음부터는 영문으로 작성해주시면 감사하겠습니다.
