### ISSUE TITLE
import in a Swift file ?

### ISSUE THREAD

**Issue by raphh11** [devxoul/UITextView-Placeholder#33]
I want to use UITextView-Placeholder, I've installed it with Cocoapods but now I'm wondering how I should import it in order to use it in my Swift file. Thanks!

**Comment by devxoul** [comment]
@raphh11, You can do:

```swift
import UITextView_Placeholder
```

**Comment by raphh11** [comment]
Ok thanks! You can close the issue, sorry for this it was pretty simple actually!
