### ISSUE TITLE
Placeholder doesn't appear until after typing and deleting

### ISSUE THREAD

**Issue by chrise86** [devxoul/UITextView-Placeholder#4]
The placeholder is hidden unless you type and delete the text, then it appears

**Comment by devxoul** [comment]
Could you please tell me your test environment? Latest version of UITextView-Placeholder seems to work in demo project.

**Comment by devxoul** [comment]
Ping @chrise86

**Comment by chrise86** [comment]
Sorry, I get the feeling this was causing via another Pod/library I was using, apologies.

Closing for now, if I encounter it again I will let you know. Thanks!

**Comment by devxoul** [comment]
Great, thanks! :smile:
