### ISSUE TITLE
@import UIKit;

### ISSUE THREAD

**Issue by 555cyril** [devxoul/UITextView-Placeholder#41]
While compilation in UITextView+Placeholder.h I have a error "Use @import when modules are disabed". Unfortunately I cannot add use_frameworks! to my pod file.
Please replace @import UIKit; with #import <UIKit/UIKit.h> in header file

**Comment by devxoul** [comment]
How did you setup UITextView-Placeholder?

**Comment by ZengWeiJun** [comment]
So do i.Please replace @import UIKit; with #import <UIKit/UIKit.h> in header file,it is start work

**Comment by devxoul** [comment]
#62 fixes this. Please feel free to reopen it if you still have a problem!
