### ISSUE TITLE
Multi placeholder string for one uitextview

### ISSUE THREAD

**Issue by Ashutos39** [devxoul/UITextView-Placeholder#46]
how to add the placeholder for Arabic and English for the same uitextview if that uitextview code is in my storyboard.i have created the outlet for that too.

**Comment by devxoul** [comment]
Is that available in `UITextField`?

**Comment by Ashutos39** [comment]
my question was how to add that in programmatically for English and  Arabic
for the same text field, which I fixed later I got that answer too.

**Comment by devxoul** [comment]
I can't imagine the English and Arabic placeholders in a same place.

**Comment by Ashutos39** [comment]
no, it's for if u change the language we can give it programmatically for
the different language the same placeholder.

**Comment by devxoul** [comment]
This is not a placeholder issue, you can just use `NSLocalizedString`.

**Comment by Ashutos39** [comment]
yeah, I solved it thanks for your valuable time.
