### ISSUE TITLE
iOS6 not support

### ISSUE THREAD

**Issue by culmek** [devxoul/UITextView-Placeholder#6]
@property(nonatomic,readonly) NSTextContainer *textContainer NS_AVAILABLE_IOS(7_0);

your code:
        x = self.textContainer.lineFragmentPadding + self.textContainerInset.left;
        y = self.textContainerInset.top;
        width = (CGRectGetWidth(self.bounds) - x - self.textContainer.lineFragmentPadding
                         - self.textContainerInset.right);

could I set the default value, so I can run in iOS6 ??
        // lineFragmentPadding default 5.0
        // textContainerInset = (top = 8, left = 0, bottom = 8, right = 0)

**Comment by devxoul** [comment]
Hello,
I made a patch for this issue, could you please test with `ios6` branch?

**Comment by culmek** [comment]
Yes，it can run...
But I think it's not good to use default value..(Use iOS6 property may be better if it has)
And your podspec's platform should set to 6.0 ?

**Comment by devxoul** [comment]
Which properties can I use for iOS 6?

**Comment by culmek** [comment]
I said IF it has properties in iOS6... 
But I did't see..
And your podspec's platform should set to 6.0 ? Cause my project deployment is 6.0, Cocoapods can't pod.
Thanks a lot.

**Comment by devxoul** [comment]
I just merged #7 and pushed 1.0.7 to CocoaPods. If it has a problem (such as magic numbers), please tell me.
Thank you!
