### ISSUE TITLE
willDealloc never execute

### ISSUE THREAD

**Issue by culmek** [devxoul/UITextView-Placeholder#8]
I have found an another problem,  willDealloc never execute.
So It can't  execute   [[NSNotificationCenter defaultCenter] removeObserver:self];    in  willDealloc's block method  ?

When I remove   [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(updatePlaceholderLabel)
                                                     name:UITextViewTextDidChangeNotification
                                                   object:self];

The below mothod did't exec either..
- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary *)change
                       context:(void *)context {
    [self updatePlaceholderLabel];
}

**Comment by devxoul** [comment]
@culmek,
I didn't realize that `DeallocHooker` is not working. I'll take a look for a while.
Thank you for you report!

**Comment by culmek** [comment]
I have found some problems..

// all uitextviews will be changed "dealloc" method to "swizzledDealloc", it's bad

+ (void)load {
    [super load];
    
    // is this the best solution?
    method_exchangeImplementations(class_getInstanceMethod(self.class, NSSelectorFromString(@"dealloc")),
                                   class_getInstanceMethod(self.class, @selector(swizzledDealloc)));
}

- (void)swizzledDealloc {
    // it can be caused a dead cycle ??

//    [self swizzledDealloc];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    // this will be crash cause some textviews didn't addObserver..
    for (NSString *key in self.class.observingKeys) {
        [self removeObserver:self forKeyPath:key];
    }
}

// here is useless, cause observeValueForKeyPath.. method didn't exec
        for (NSString *key in self.class.observingKeys) {
            [self addObserver:self forKeyPath:key options:NSKeyValueObservingOptionNew context:nil];
        }


And I think you should use navigationcontroller to push a viewcontroller which has a uitextview(set placeholder), then override the dealloc method to see dealloc() is exec or not ??

**Comment by devxoul** [comment]
Yes, also we can test `dealloc` with a temporary method.

```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    [self test];
}

- (void)test {
    UITextView *textView = [[UITextView alloc] init];
    textView.placeholder = @"placeholder";
}
```

`textView` would be dealloced at the end of `test`.


Anyway, how about using try-catch to catch unregistered observers? https://github.com/devxoul/UITextView-Placeholder/commit/a3402091ed8cc9bc08e4d70fc780f095c690c34e

**Comment by culmek** [comment]
Sorry, It must be added to self.view  just like below:
   UITextView *textView = [[UITextView alloc] init];
    [self.view addSubview:textView];
It will be crash cause textView didn't set placeholder which didn't exec the below method in 
 (   [self addObserver:self forKeyPath:key options:NSKeyValueObservingOptionNew context:nil];  )


And, I expect you see my 3 problems :
1、
// all uitextviews will be changed "dealloc" method to "swizzledDealloc", it's bad
//+ (void)load {

2、
//    // it can be caused a dead cycle ??
////    [self swizzledDealloc];

3、
        // here is useless, cause observeValueForKeyPath.. method didn't exec
//        for (NSString *key in self.class.observingKeys) {
//            [self addObserver:self forKeyPath:key options:NSKeyValueObservingOptionNew context:nil];
//        }

**Comment by devxoul** [comment]
Did you check [this commit](https://github.com/devxoul/UITextView-Placeholder/commit/a3402091ed8cc9bc08e4d70fc780f095c690c34e)? It prevents from being crashed if there is no placeholder set.

```objc
UITextView *textView = [[UITextView alloc] init];
[self.view addSubview:textView];
```

1. Yes. Sadly but it is only possible solution I found until now.
2. Nope. `dealloc` now became `swizzledDealloc`, so calling `swizzledDealloc` means calling original `dealloc`.
3. I cannot understand what you mean. Did you mean [this highlighted code](https://github.com/devxoul/UITextView-Placeholder/blob/dealloc-swizzle/UITextView%2BPlaceholder/UITextView%2BPlaceholder.m#L103-L105) is not being executed?

**Comment by culmek** [comment]
Yes,I have check your this commit (@try...@catch), But it's crashed either, case I use two viewcontrollers (viewContollerA and viewControllerB, A push B, and B has a UITextView, while B pop, it will be crashed)

3、I want to say the below method didn't execute
#pragma mark - KVO

- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary *)change
                       context:(void *)context {
    [self updatePlaceholderLabel];
}

**Comment by devxoul** [comment]
I just pushed another commit, could you please test with https://github.com/devxoul/UITextView-Placeholder/commit/0854b1df52532ce1ed1cfd68207cb5b1b4741a6e commit? I placed `[self swizzledDealloc]` at the end of `swizzledDealloc` method, and it seemed not being crashed after popping view controller.

How can I test that observing method won't be called? It'll be executed when setting observing properties such as `font`, `frame`, `text`:

```objc
UITextView *textView = [[UITextView alloc] init];
textView.placeholder = @"Some placeholder";
textView.font = [UIFont systemFontOfSize:15]; // KVO method would be called after this line.
```

**Comment by culmek** [comment]
Yes, It can do it

**Comment by devxoul** [comment]
OK, then I can merge it! Thank you for you time, @culmek :smile:
